import { Exercise, Quote, WeeklySchedule } from './types';

export const WORKOUT_PLAN: Exercise[] = [
  // --- Lower Body ---
  {
    id: 1,
    name: 'Barbell Squats',
    sets: '4',
    reps: '8-12',
    description: 'A compound exercise that works the quadriceps, glutes, and hamstrings. The foundation of lower body strength.',
    imageUrl: 'https://img.youtube.com/vi/_RlRDWO2jfg/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/embed/_RlRDWO2jfg',
    imageUrlFemale: 'https://img.youtube.com/vi/U3HlEF_E9fo/hqdefault.jpg',
    videoUrlFemale: 'https://www.youtube.com/embed/U3HlEF_E9fo',
    muscleGroups: ['Quadriceps', 'Glutes', 'Hamstrings', 'Core'],
    equipment: 'Barbell, Squat Rack',
    formTips: [
      'Keep your chest up and back straight.',
      'Descend until thighs are at least parallel to the floor.',
      'Drive through your heels to return to the starting position.',
    ],
    difficulty: 'Intermediate',
  },
  {
    id: 2,
    name: 'Goblet Squats',
    sets: '3-4',
    reps: '10-15',
    description: 'An excellent squat variation for learning proper form and engaging the core, quads, and glutes.',
    imageUrl: 'https://img.youtube.com/vi/Me_Wh_Tw_V8/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/embed/Me_Wh_Tw_V8',
    imageUrlFemale: 'https://img.youtube.com/vi/w9_t-s7s3gQ/hqdefault.jpg',
    videoUrlFemale: 'https://www.youtube.com/embed/w9_t-s7s3gQ',
    muscleGroups: ['Quadriceps', 'Glutes', 'Core', 'Hamstrings'],
    equipment: 'Dumbbell or Kettlebell',
    formTips: [
      'Hold the weight against your chest with both hands.',
      'Keep your back straight and chest up.',
      'Lower down as if sitting in a chair, keeping your knees out.',
      'Drive through your heels to stand back up.'
    ],
    difficulty: 'Beginner',
  },
  {
    id: 3,
    name: 'Conventional Deadlifts',
    sets: '3',
    reps: '5-8',
    description: 'A full-body exercise that emphasizes the posterior chain, including the back, glutes, and hamstrings.',
    imageUrl: 'https://img.youtube.com/vi/1ZXobu7JpMo/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/embed/1ZXobu7JpMo',
    imageUrlFemale: 'https://img.youtube.com/vi/l_M0gVTg3PE/hqdefault.jpg',
    videoUrlFemale: 'https://www.youtube.com/embed/l_M0gVTg3PE',
    muscleGroups: ['Posterior Chain', 'Glutes', 'Hamstrings', 'Back'],
    equipment: 'Barbell',
    formTips: [
        'Maintain a neutral spine throughout the lift.',
        'Keep the bar close to your body.',
        'Engage your lats to protect your back.'
    ],
    difficulty: 'Advanced',
  },
  {
    id: 4,
    name: 'Romanian Deadlifts',
    sets: '3-4',
    reps: '8-12',
    description: 'Focuses on hamstring and glute development with a hip-hinge movement, keeping legs relatively straight.',
    imageUrl: 'https://img.youtube.com/vi/2SHsk9A_v1s/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/embed/2SHsk9A_v1s',
    imageUrlFemale: 'https://img.youtube.com/vi/8-JTwVv6dK8/hqdefault.jpg',
    videoUrlFemale: 'https://www.youtube.com/embed/8-JTwVv6dK8',
    muscleGroups: ['Hamstrings', 'Glutes', 'Erector Spinae'],
    equipment: 'Barbell or Dumbbells',
    formTips: [
        'Keep a slight bend in your knees but do not squat.',
        'Hinge at your hips, pushing your butt back.',
        'Lower the weight until you feel a deep stretch in your hamstrings.',
    ],
    difficulty: 'Intermediate',
  },
  {
    id: 5,
    name: 'Walking Lunges',
    sets: '3',
    reps: '10-15 per leg',
    description: 'Targets the quadriceps, glutes, and hamstrings, while also improving balance and coordination.',
    imageUrl: 'https://img.youtube.com/vi/D7KaRcUTQeE/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/embed/D7KaRcUTQeE',
    imageUrlFemale: 'https://img.youtube.com/vi/YfKjE_t7H-I/hqdefault.jpg',
    videoUrlFemale: 'https://www.youtube.com/embed/YfKjE_t7H-I',
    muscleGroups: ['Quadriceps', 'Glutes', 'Hamstrings'],
    equipment: 'Dumbbells or Bodyweight',
    formTips: [
      'Take a controlled step forward.',
      'Lower your hips until both knees are at a 90-degree angle.',
      'Keep your front knee aligned with your ankle.',
    ],
    difficulty: 'Beginner',
  },
  {
    id: 6,
    name: 'Leg Press',
    sets: '4',
    reps: '10-15',
    description: 'A machine-based exercise to build quad, hamstring, and glute strength without stressing the lower back.',
    imageUrl: 'https://img.youtube.com/vi/sEM_p9wLtrY/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/embed/sEM_p9wLtrY',
    imageUrlFemale: 'https://img.youtube.com/vi/Gk--QJdYt_4/hqdefault.jpg',
    videoUrlFemale: 'https://www.youtube.com/embed/Gk--QJdYt_4',
    muscleGroups: ['Quadriceps', 'Glutes', 'Hamstrings'],
    equipment: 'Leg Press Machine',
    formTips: [
      'Place feet shoulder-width apart on the platform.',
      'Do not lock your knees at the top of the movement.',
      'Control the weight on both the push and return phases.',
    ],
    difficulty: 'Beginner',
  },
  {
    id: 7,
    name: 'Calf Raises',
    sets: '4',
    reps: '15-20',
    description: 'Isolates and strengthens the calf muscles (gastrocnemius and soleus).',
    imageUrl: 'https://img.youtube.com/vi/Jfl_3ws77qI/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/embed/Jfl_3ws77qI',
    imageUrlFemale: 'https://img.youtube.com/vi/wxwYBFh3_P4/hqdefault.jpg',
    videoUrlFemale: 'https://www.youtube.com/embed/wxwYBFh3_P4',
    muscleGroups: ['Calves'],
    equipment: 'Bodyweight, Dumbbells, or Machine',
    formTips: [
      'Perform the full range of motion, from a deep stretch to a full contraction.',
      'Pause at the top of the movement to squeeze the calf muscles.',
      'Avoid bouncing; use a controlled tempo.',
    ],
    difficulty: 'Beginner',
  },
  // --- Upper Body Push ---
  {
    id: 8,
    name: 'Bench Press',
    sets: '4',
    reps: '8-12',
    description: 'Targets the pectoral muscles, as well as the anterior deltoids and triceps.',
    imageUrl: 'https://img.youtube.com/vi/gRVjAtPip0Y/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/embed/gRVjAtPip0Y',
    imageUrlFemale: 'https://img.youtube.com/vi/33aGk2aJ2b0/hqdefault.jpg',
    videoUrlFemale: 'https://www.youtube.com/embed/33aGk2aJ2b0',
    muscleGroups: ['Pectorals', 'Deltoids', 'Triceps'],
    equipment: 'Barbell, Bench',
    formTips: [
      'Keep your feet flat on the floor.',
      'Lower the bar to your mid-chest.',
      'Press the bar up without locking your elbows.',
    ],
    difficulty: 'Intermediate',
  },
  {
    id: 9,
    name: 'Push-Ups',
    sets: '3',
    reps: 'To Failure',
    description: 'A classic bodyweight exercise for building chest, shoulder, and tricep strength.',
    imageUrl: 'https://img.youtube.com/vi/IODxDxX7oi4/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/embed/IODxDxX7oi4',
    imageUrlFemale: 'https://img.youtube.com/vi/wZ8L-IqC64I/hqdefault.jpg',
    videoUrlFemale: 'https://www.youtube.com/embed/wZ8L-IqC64I',
    muscleGroups: ['Pectorals', 'Deltoids', 'Triceps', 'Core'],
    equipment: 'Bodyweight',
    formTips: [
      'Keep your body in a straight line from head to heels.',
      'Lower your chest to just above the floor.',
      'Keep your elbows tucked in at a 45-degree angle, not flared out.',
    ],
    difficulty: 'Beginner',
  },
  {
    id: 10,
    name: 'Overhead Press',
    sets: '4',
    reps: '8-12',
    description: 'Builds shoulder strength and size, targeting the deltoids and triceps.',
    imageUrl: 'https://img.youtube.com/vi/2yjwXTZQDDI/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/embed/2yjwXTZQDDI',
    imageUrlFemale: 'https://img.youtube.com/vi/6vRI33-ekyU/hqdefault.jpg',
    videoUrlFemale: 'https://www.youtube.com/embed/6vRI33-ekyU',
    muscleGroups: ['Deltoids', 'Triceps', 'Upper Pectorals'],
    equipment: 'Barbell or Dumbbells',
    formTips: [
      'Keep your core tight to avoid arching your back.',
      'Press the weight directly overhead.',
      'Control the weight on the way down.',
    ],
    difficulty: 'Intermediate',
  },
  {
    id: 11,
    name: 'Tricep Dips',
    sets: '3',
    reps: '10-15',
    description: 'Uses your bodyweight to effectively target and build the tricep muscles.',
    imageUrl: 'https://img.youtube.com/vi/6kALsYw4OmA/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/embed/6kALsYw4OmA',
    imageUrlFemale: 'https://img.youtube.com/vi/0326dy_-CzM/hqdefault.jpg',
    videoUrlFemale: 'https://www.youtube.com/embed/0326dy_-CzM',
    muscleGroups: ['Triceps', 'Deltoids', 'Pectorals'],
    equipment: 'Parallel Bars or Bench',
    formTips: [
      'Lower your body until your elbows are at a 90-degree angle.',
      'Keep your chest up and shoulders back.',
      'Focus on using your triceps to push back up.',
    ],
    difficulty: 'Intermediate',
  },
  // --- Upper Body Pull ---
  {
    id: 12,
    name: 'Pull-Ups',
    sets: '3',
    reps: 'To Failure',
    description: 'An excellent bodyweight exercise for developing back and bicep strength.',
    imageUrl: 'https://img.youtube.com/vi/poyrpyrhTEc/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/embed/poyrpyrhTEc',
    imageUrlFemale: 'https://img.youtube.com/vi/Kbe3pY84y5I/hqdefault.jpg',
    videoUrlFemale: 'https://www.youtube.com/embed/Kbe3pY84y5I',
    muscleGroups: ['Latissimus Dorsi', 'Biceps', 'Rhomboids'],
    equipment: 'Pull-up Bar',
    formTips: [
      'Start from a dead hang.',
      'Pull your chest towards the bar.',
      'Avoid using momentum or swinging.',
    ],
    difficulty: 'Advanced',
  },
  {
    id: 13,
    name: 'Bent-Over Rows',
    sets: '4',
    reps: '8-12',
    description: 'Strengthens the middle back, lats, and biceps.',
    imageUrl: 'https://img.youtube.com/vi/V_L2pZ5g-L4/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/embed/V_L2pZ5g-L4',
    imageUrlFemale: 'https://img.youtube.com/vi/kBWAon7NJkc/hqdefault.jpg',
    videoUrlFemale: 'https://www.youtube.com/embed/kBWAon7NJkc',
    muscleGroups: ['Middle Back', 'Lats', 'Biceps', 'Rhomboids'],
    equipment: 'Barbell or Dumbbells',
    formTips: [
      'Hinge at your hips, keeping your back straight.',
      'Pull the weight towards your lower chest.',
      'Squeeze your shoulder blades together at the top.',
    ],
    difficulty: 'Intermediate',
  },
   {
    id: 14,
    name: 'Lat Pulldown',
    sets: '3-4',
    reps: '10-15',
    description: 'A machine-based exercise that targets the latissimus dorsi, great for building a wider back.',
    imageUrl: 'https://img.youtube.com/vi/0oe_w-A2-nU/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/embed/0oe_w-A2-nU',
    imageUrlFemale: 'https://img.youtube.com/vi/8y4A-A_d2Y4/hqdefault.jpg',
    videoUrlFemale: 'https://www.youtube.com/embed/8y4A-A_d2Y4',
    muscleGroups: ['Latissimus Dorsi', 'Biceps', 'Middle Back'],
    equipment: 'Lat Pulldown Machine',
    formTips: [
      'Keep your chest up and slightly lean back.',
      'Pull the bar down to your upper chest.',
      'Focus on squeezing your lats, not just pulling with your arms.',
    ],
    difficulty: 'Beginner',
  },
  {
    id: 15,
    name: 'Bicep Curls',
    sets: '3',
    reps: '10-15',
    description: 'Isolates the biceps to build arm size and strength.',
    imageUrl: 'https://img.youtube.com/vi/av7-8G_d_BA/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/embed/av7-8G_d_BA',
    imageUrlFemale: 'https://img.youtube.com/vi/32LKCbYg2kM/hqdefault.jpg',
    videoUrlFemale: 'https://www.youtube.com/embed/32LKCbYg2kM',
    muscleGroups: ['Biceps'],
    equipment: 'Dumbbells or Barbell',
    formTips: [
      'Keep your elbows pinned to your sides.',
      'Avoid using momentum or swinging your body.',
      'Control the weight on the way down for a full contraction.',
    ],
    difficulty: 'Beginner',
  },
  // --- Core & Abs ---
  {
    id: 16,
    name: 'Plank',
    sets: '3',
    reps: '60 seconds',
    description: 'A core-strengthening exercise that improves posture and stability.',
    imageUrl: 'https://img.youtube.com/vi/pSHjTRCQxIw/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/embed/pSHjTRCQxIw',
    imageUrlFemale: 'https://img.youtube.com/vi/DHvsgDCI1aM/hqdefault.jpg',
    videoUrlFemale: 'https://www.youtube.com/embed/DHvsgDCI1aM',
    muscleGroups: ['Core', 'Abdominals', 'Obliques'],
    equipment: 'Bodyweight',
    formTips: [
      'Keep your body in a a straight line from head to heels.',
      'Engage your core and glutes.',
      'Don\'t let your hips sag.',
    ],
    difficulty: 'Beginner',
  },
  {
    id: 17,
    name: 'Hanging Leg Raises',
    sets: '3',
    reps: '10-15',
    description: 'An advanced core exercise that targets the lower abdominals and hip flexors.',
    imageUrl: 'https://img.youtube.com/vi/Pr1ieGZ5atk/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/embed/Pr1ieGZ5atk',
    imageUrlFemale: 'https://img.youtube.com/vi/4Tfd9s3D_zk/hqdefault.jpg',
    videoUrlFemale: 'https://www.youtube.com/embed/4Tfd9s3D_zk',
    muscleGroups: ['Lower Abdominals', 'Hip Flexors', 'Obliques'],
    equipment: 'Pull-up Bar',
    formTips: [
      'Hang from the bar with your legs straight.',
      'Raise your legs until they are parallel to the floor, or higher.',
      'Control the movement on the way down; avoid swinging.',
    ],
    difficulty: 'Advanced',
  },
  {
    id: 18,
    name: 'Russian Twists',
    sets: '3',
    reps: '15-20 per side',
    description: 'Targets the obliques and improves rotational core strength.',
    imageUrl: 'https://img.youtube.com/vi/wkD8rjkodUI/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/embed/wkD8rjkodUI',
    imageUrlFemale: 'https://img.youtube.com/vi/DJQ1_oG0k6s/hqdefault.jpg',
    videoUrlFemale: 'https://www.youtube.com/embed/DJQ1_oG0k6s',
    muscleGroups: ['Obliques', 'Abdominals', 'Lower Back'],
    equipment: 'Medicine Ball, Weight Plate, or Bodyweight',
    formTips: [
      'Lean back with your knees bent, keeping your back straight.',
      'Twist your torso from side to side, touching the weight to the floor.',
      'Keep your feet off the ground for an added challenge.',
    ],
    difficulty: 'Beginner',
  },
  // --- Full Body & Functional ---
  {
    id: 19,
    name: 'Kettlebell Swings',
    sets: '4',
    reps: '15-20',
    description: 'A dynamic, explosive exercise that builds power in the posterior chain and improves cardiovascular fitness.',
    imageUrl: 'https://img.youtube.com/vi/YSxHifyI6s8/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/embed/YSxHifyI6s8',
    imageUrlFemale: 'https://img.youtube.com/vi/i3pI8N-p-So/hqdefault.jpg',
    videoUrlFemale: 'https://www.youtube.com/embed/i3pI8N-p-So',
    muscleGroups: ['Glutes', 'Hamstrings', 'Core', 'Back'],
    equipment: 'Kettlebell',
    formTips: [
      'The movement is a hip hinge, not a squat.',
      'Use your hips and glutes to drive the kettlebell up.',
      'Keep your arms relaxed; they are just there to guide the weight.',
    ],
    difficulty: 'Advanced',
  },
  {
    id: 20,
    name: 'Burpees',
    sets: '3',
    reps: '10-15',
    description: 'A high-intensity, full-body exercise that combines a squat, push-up, and jump. Excellent for conditioning.',
    imageUrl: 'https://img.youtube.com/vi/dZgVxmf6jkA/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/embed/dZgVxmf6jkA',
    imageUrlFemale: 'https://img.youtube.com/vi/xQyFuV2-w7o/hqdefault.jpg',
    videoUrlFemale: 'https://www.youtube.com/embed/xQyFuV2-w7o',
    muscleGroups: ['Full Body', 'Cardio'],
    equipment: 'Bodyweight',
    formTips: [
      'Perform each component of the movement with good form.',
      'Keep your core engaged throughout.',
      'Land softly on your feet after the jump.',
    ],
    difficulty: 'Intermediate',
  },
  {
    id: 21,
    name: 'Farmer\'s Walk',
    sets: '3',
    reps: '30-45 seconds',
    description: 'Builds grip strength, core stability, and overall toughness by carrying heavy weights for a distance.',
    imageUrl: 'https://img.youtube.com/vi/kAF5d_gY4NU/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/embed/kAF5d_gY4NU',
    imageUrlFemale: 'https://img.youtube.com/vi/VDi3Ko8drto/hqdefault.jpg',
    videoUrlFemale: 'https://www.youtube.com/embed/VDi3Ko8drto',
    muscleGroups: ['Grip', 'Forearms', 'Core', 'Traps', 'Full Body'],
    equipment: 'Dumbbells, Kettlebells, or Farmer\'s Handles',
    formTips: [
      'Keep your chest up and shoulders pulled back.',
      'Take short, quick steps.',
      'Brace your core to prevent leaning to one side.',
    ],
    difficulty: 'Intermediate',
  },
  // --- NEW EXERCISES ---
  {
    id: 22,
    name: 'Dumbbell Flyes',
    sets: '3',
    reps: '10-15',
    description: 'An isolation exercise that targets the pectoral muscles, focusing on stretching and contraction.',
    imageUrl: 'https://img.youtube.com/vi/eozb-ti_Sac/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/embed/eozb-ti_Sac',
    imageUrlFemale: 'https://img.youtube.com/vi/D-oGqg--Q8k/hqdefault.jpg',
    videoUrlFemale: 'https://www.youtube.com/embed/D-oGqg--Q8k',
    muscleGroups: ['Pectorals'],
    equipment: 'Dumbbells, Bench',
    formTips: [
      'Lie on a flat bench with a dumbbell in each hand.',
      'Keep a slight bend in your elbows throughout the movement.',
      'Lower the weights in a wide arc until you feel a stretch in your chest.',
      'Squeeze your chest muscles to bring the weights back to the starting position.'
    ],
    difficulty: 'Intermediate',
  },
  {
    id: 23,
    name: 'Arnold Press',
    sets: '3',
    reps: '10-12',
    description: 'A unique shoulder press variation that hits all three heads of the deltoid.',
    imageUrl: 'https://img.youtube.com/vi/6Z15_WdXmVw/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/embed/6Z15_WdXmVw',
    imageUrlFemale: 'https://img.youtube.com/vi/3ml7o7a_A-8/hqdefault.jpg',
    videoUrlFemale: 'https://www.youtube.com/embed/3ml7o7a_A-8',
    muscleGroups: ['Deltoids', 'Triceps'],
    equipment: 'Dumbbells',
    formTips: [
      'Start with palms facing you, dumbbells at shoulder height.',
      'As you press up, rotate your palms to face forward.',
      'Reverse the motion on the way down.',
      'Keep the movement smooth and controlled.'
    ],
    difficulty: 'Intermediate',
  },
  {
    id: 24,
    name: 'Overhead Tricep Extensions',
    sets: '3',
    reps: '10-15',
    description: 'Isolates the triceps, particularly the long head, for complete arm development.',
    imageUrl: 'https://img.youtube.com/vi/3a-30-C-k6k/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/embed/3a-30-C-k6k',
    imageUrlFemale: 'https://img.youtube.com/vi/Yb8sZczo2FY/hqdefault.jpg',
    videoUrlFemale: 'https://www.youtube.com/embed/Yb8sZczo2FY',
    muscleGroups: ['Triceps'],
    equipment: 'Dumbbell or Cable Machine',
    formTips: [
      'Hold a single dumbbell with both hands overhead.',
      'Lower the weight behind your head by bending your elbows.',
      'Keep your upper arms stationary throughout the movement.',
      'Extend your arms to lift the weight back up, focusing on the tricep contraction.'
    ],
    difficulty: 'Beginner',
  },
  {
    id: 25,
    name: 'Hammer Curls',
    sets: '3',
    reps: '10-15 per arm',
    description: 'A bicep curl variation with a neutral grip that also targets the brachialis and forearms.',
    imageUrl: 'https://img.youtube.com/vi/zC3nLH_6WJQ/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/embed/zC3nLH_6WJQ',
    imageUrlFemale: 'https://img.youtube.com/vi/TwD-2Esk-YE/hqdefault.jpg',
    videoUrlFemale: 'https://www.youtube.com/embed/TwD-2Esk-YE',
    muscleGroups: ['Biceps', 'Brachialis', 'Forearms'],
    equipment: 'Dumbbells',
    formTips: [
      'Hold dumbbells with palms facing each other (neutral grip).',
      'Curl the weight up, keeping your elbows locked at your sides.',
      'Squeeze at the top and slowly lower the weight.',
      'Avoid swinging the dumbbells.'
    ],
    difficulty: 'Beginner',
  },
  {
    id: 26,
    name: 'Face Pulls',
    sets: '3-4',
    reps: '15-20',
    description: 'An excellent exercise for improving posture and strengthening the rear deltoids and upper back muscles.',
    imageUrl: 'https://img.youtube.com/vi/0po4j_67mSs/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/embed/0po4j_67mSs',
    imageUrlFemale: 'https://img.youtube.com/vi/HSoHeSjvId8/hqdefault.jpg',
    videoUrlFemale: 'https://www.youtube.com/embed/HSoHeSjvId8',
    muscleGroups: ['Rear Deltoids', 'Rhomboids', 'Trapezius'],
    equipment: 'Cable Machine with Rope Attachment',
    formTips: [
      'Set the cable to face height.',
      'Pull the ropes towards your face, aiming to get your hands by your ears.',
      'Focus on squeezing your shoulder blades together.',
      'Keep your elbows high and externally rotate your shoulders at the end of the pull.'
    ],
    difficulty: 'Beginner',
  }
];

export const MOTIVATIONAL_QUOTES: Quote[] = [
  { text: "The only bad workout is the one that didn't happen.", author: 'Unknown' },
  { text: 'Success isn’t always about greatness. It’s about consistency. Consistent hard work leads to success. Greatness will come.', author: 'Dwayne Johnson' },
  { text: 'The last three or four reps is what makes the muscle grow. This area of pain divides a champion from someone who is not a champion.', author: 'Arnold Schwarzenegger' },
  { text: 'The body achieves what the mind believes.', author: 'Napoleon Hill' },
  { text: 'You have to think it before you can do it. The mind is what makes it all possible.', author: 'Kai Greene' },
  { text: 'Push yourself because no one else is going to do it for you.', author: 'Unknown' },
];

export const WEEKLY_SCHEDULE: WeeklySchedule = {
    1: { day: 'Monday', focus: 'Back Workouts', exerciseIds: [12, 13, 14, 26] },
    2: { day: 'Tuesday', focus: 'Bicep Workouts', exerciseIds: [15, 25] },
    3: { day: 'Wednesday', focus: 'Chest Workouts', exerciseIds: [8, 9, 22] },
    4: { day: 'Thursday', focus: 'Tricep Workouts', exerciseIds: [11, 24] },
    5: { day: 'Friday', focus: 'Shoulder Workouts', exerciseIds: [10, 23, 26] },
    6: { day: 'Saturday', focus: 'Leg Workouts', exerciseIds: [1, 6, 5, 7] },
    0: { day: 'Sunday', focus: 'Rest Day', exerciseIds: [], isRestDay: true },
};